[package]
authors = ["Uzaaft <muaf@nmbu.no>"]
name = "rustyworm"
version = "0.1.0"
edition = "2018"

[lib]
name = "maturin_starter"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.4"
pyo3 = { version = "0.15.1", features = ["extension-module"] }
